name: kyleguilfoyle-website
static_sites:
- name: kyleguilfoyle-website
  source_dir: /public
  github:
    repo: guestgetter/kyleguilfoyle-website
    branch: main
  build_command: npm run build
  environment_slug: html
  headers:
  - pattern: "/**"
    headers:
    - key: "X-Content-Type-Options"
      value: "nosniff"
    - key: "X-Frame-Options" 
      value: "DENY"
    - key: "X-XSS-Protection"
      value: "1; mode=block"
    - key: "Referrer-Policy"
      value: "strict-origin-when-cross-origin"
    - key: "Permissions-Policy"
      value: "camera=(), microphone=(), geolocation=()"
    - key: "Strict-Transport-Security"
      value: "max-age=31536000; includeSubDomains"
    - key: "Content-Security-Policy"
      value: "default-src 'self'; script-src 'self' 'unsafe-inline' https://www.googletagmanager.com https://www.clarity.ms; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https:; connect-src 'self' https://www.google-analytics.com https://www.clarity.ms;"
  catchall_document: index.html
  error_document: 404.html 