# This workflow is disabled since we're using Digital Ocean for deployment
# To re-enable, uncomment the lines below

# name: Build and Deploy
# 
# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]
# 
# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest
#     
#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v4
#       
#     - name: Setup Node.js
#       uses: actions/setup-node@v4
#       with:
#         node-version: '18'
#         cache: 'npm'
#         
#     - name: Install dependencies
#       run: npm ci
#       
#     - name: Build site with Notion content
#       env:
#         NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
#         NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
#       run: npm run build
#       
#     - name: Deploy to GitHub Pages (optional)
#       uses: peaceiris/actions-gh-pages@v3
#       if: github.ref == 'refs/heads/main'
#       with:
#         github_token: ${{ secrets.GITHUB_TOKEN }}
#         publish_dir: ./public 